$(function(){
    $('#fullpage').fullpage({
        autoScrolling:true,
        scrollHorizontally:true,
        navigation:true,
        anchors:['section1','section2','section3','section4','section5'],
        sectionsColor:['#ccc','#bbb','pink','skyblue','ivory'],
    })
})